include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # ⭐ Performance Rules
    prefer_const_constructors: true                  # Bolega: 'const' lagao jahan lag sakta hai
    prefer_const_declarations: true                  # Constants ko declare karne par guide karega
    prefer_const_constructors_in_immutables: true   # Custom Widgets ke constructor ko const banwayega
    prefer_const_literals_to_create_immutables: true # Lists/Maps ke sath const lagwayega

    # 🧹 Clean Code Rules
    avoid_unnecessary_containers: true              # Fuzool Containers lagane par toke ga
    prefer_conditional_assignment: true
    unnecessary_string_interpolations: true
    use_build_context_synchronously: true            # Async operations mein context usage ki safety check